#!/bin/bash

# Params list (use "-p" or "--params")
# 1 - Folder name in /mnt
# 2 - Yandex Disc login
# 3 - Yandex Disc password

# Get init mode param
param_mode=$1

# Set user params
if [[ "$param_mode" == "-p" ]] || [[ "$param_mode" == "--params" ]]; then
  param_mnt_folder=$2
  param_login=$3
  param_pass=$4
else
  echo "   Enter parameters (3 steps)"
  read -rp "1. Folder name: " param_mnt_folder
  read -rp "2. Yandex login: " param_login
  read -rp "3. Yandex pass: " param_pass
fi

# Modify params
mnt_folder="/mnt/${param_mnt_folder}"

# Print params
cGreen="\e[1;32m"
cYellow="\e[1;33m"
cEnd="\e[0m"

echo "=================================================="
echo -e "${cGreen}1. Folder name:  ${cYellow}${param_mnt_folder}${cEnd}"
echo -e "${cGreen}2. Yandex login: ${cYellow}${param_login}${cEnd}"
echo -e "${cGreen}3. Yandex pass:  ${cYellow}${param_pass}${cEnd}"
echo "=================================================="

if ! [[ "$param_mode" == "-p" ]] && ! [[ "$param_mode" == "--params" ]]; then
  while true; do
    read -rp "It is all OK? Can we proceed? [y|n]: " yn
    case $yn in
    [Yy]*) break ;;
    [Nn]*) exit ;;
    *) echo "It is all OK? Can we proceed? [y|n]: " ;;
    esac
  done
fi

# Update & upgrade
apt -y update
apt -y upgrade
apt -y dist-upgrade

# Hide interactive screens
export DEBIAN_FRONTEND=noninteractive

# Install dependencies
apt -y install davfs2

# Make folder
mkdir -p "${mnt_folder}"

# Configuration
echo "https://webdav.yandex.ru ${mnt_folder} davfs user,rw,nofail,_netdev,file_mode=0777,dir_mode=0777 0 0" >> /etc/fstab
echo "https://webdav.yandex.ru ${param_login} ${param_pass}" >> /etc/davfs2/secrets

